version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: worker
      WORDPRESS_DB_PASSWORD: AxziETziuGyXbsHmwYCt
      WORDPRESS_DB_NAME: wordpressdb
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: wordpressdb
      MYSQL_USER: worker
      MYSQL_PASSWORD: AxziETziuGyXbsHmwYCt
      MYSQL_ROOT_PASSWORD: JdDdxdopdZyQaDuxymzT
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db: 