version: '3.1'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_USER: worker
      MYSQL_PASSWORD: ZsYFYdLaRqjOTebBnfbf
      MYSQL_DATABASE: work
      MYSQL_ROOT_PASSWORD: xtKMEIZejNxwjtDgGbOl
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  mysql-data:
